# Generated by Django 5.2.7 on 2025-12-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
