# Generated by Django 5.2.7 on 2025-12-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_options_remove_post_updated_at_post_likes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="content",
        ),
    ]
