# Generated by Django 5.2.7 on 2025-12-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_content_comment_text_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
